/*
 *                 Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is the JavaScript editor module. 
 * The Initial Developer of the Original Code is Nicolas Désy. 
 * Portions Copyright 2006 Nicolas Désy.
 * All Rights Reserved.
 */

package com.liguorien.jseditor.ui;

import com.liguorien.jseditor.stub.NewAjaxCallbackTemplateModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Set;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.EditorKit;
import org.netbeans.modules.editor.html.HTMLKit;
import org.openide.text.IndentEngine;
import org.openide.util.Lookup;

/**
 *
 * @author  Nicolas Désy and Matisse ;)
 */
public class NewAjaxCallbackTemplateView extends javax.swing.JPanel {
    
    private NewAjaxCallbackTemplateModel _model = null;
    
    /** Creates new form NewAjaxCallbackTemplateView */
    public NewAjaxCallbackTemplateView(NewAjaxCallbackTemplateModel model) {
        _model = model;
        initComponents();
        
     
        
        templateTxt.setEditorKit(HTMLKit.getKit(HTMLKit.class));
        nameTxt.setText(_model.getCallbackName());
        targetTxt.setText(_model.getTargetId());
        templateTxt.setText(_model.getTemplate());
        _model.setNeedToInclude(needToIncludeChx.isSelected());
        
        nameTxt.getDocument().addDocumentListener(new TextFieldUpdater(){
            public void onTextChanged(String text){_model.setCallbackName(text);}
        });
        
        targetTxt.getDocument().addDocumentListener(new TextFieldUpdater(){
            public void onTextChanged(String text){_model.setTargetId(text);}
        });
        
        templateTxt.getDocument().addDocumentListener(new TextFieldUpdater(){
            public void onTextChanged(String text){_model.setTemplate(text);}
        });
        
        
        
        needToIncludeChx.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                _model.setNeedToInclude(needToIncludeChx.isSelected());
            }
        });
    }
    
    private class TextFieldUpdater implements DocumentListener {
        public void onTextChanged(String text){}
        private void handleEvent(DocumentEvent e) {
            try {
                final Document doc = e.getDocument();
                onTextChanged(doc.getText(0, doc.getLength()));
            } catch (BadLocationException ex) {
                ex.printStackTrace();
            }
        }
        public void changedUpdate(DocumentEvent e) {handleEvent(e);}
        public void removeUpdate(DocumentEvent e) {handleEvent(e);}
        public void insertUpdate(DocumentEvent e) {handleEvent(e);}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        targetTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        needToIncludeChx = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        templateTxt = new javax.swing.JEditorPane();

        jLabel1.setText("Function Name");
        jLabel1.setToolTipText("Name of the generated function");

        jLabel2.setText("Target ID");
        jLabel2.setToolTipText("ID of the HTMLElement that will receive template's content with the 'innerHTML' property");

        targetTxt.setToolTipText("");

        jLabel3.setText("Template");

        needToIncludeChx.setSelected(true);
        needToIncludeChx.setText("Include \"getItems()\" function ?");
        needToIncludeChx.setToolTipText("The \"getItems()\" function is used to retreive node in the XML tree.  The function is require only if the template use a <forEach.  You can copy the function declaration and paste it to the top of the file. So all callback can share the same function to reduce filesize.");
        needToIncludeChx.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        needToIncludeChx.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jScrollPane1.setViewportView(templateTxt);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(targetTxt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(needToIncludeChx))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, nameTxt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                    .add(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nameTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(targetTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(needToIncludeChx)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JCheckBox needToIncludeChx;
    private javax.swing.JTextField targetTxt;
    private javax.swing.JEditorPane templateTxt;
    // End of variables declaration//GEN-END:variables
    
}
